42mogle/42-mogle-frontend

src/App.js
src/Pages/Home.jsx
src/Pages/Signup.jsx

refactor: components, pages 폴더 첫 글자 소문자로 변경#40

---

src/App.js
src/Components/MobileLayout.jsx
src/Pages/Login.jsx

모바일 화면 레이아웃을 MobileLayout 컴포넌트로 분리했습니다.

refactor: Add MoblieLayout.jsx #45

---

package-lock.json
package.json
src/Components/AttendanceTable.jsx
src/Pages/Home.jsx

- date-fns 라이브러리를 사용해서 yyyy년 MM월 dd일 형식으로 오늘 날짜를 변환했습니다.
- date-fns 라이브러리를 사용해서 출석 기록의 날짜와 시간을 변환했습니다.

Refactor/use date fns#50

---

src/Pages/Login.jsx

-
localhost IP에서 42mogle.com 으로 변경했습니다.

fix: 회원가입 버튼 42 oauth api redirect 주소 변경 #53

---

src/Pages/HomePage/index.jsx
src/api/apiManager.js
src/api/requestGet.js
src/api/requestPost.js

- apiManager 생성
- requestGet, requestPost 메서드 생성 (로컬에서 제대로 작동하는지 확인하는 방법을 몰라서 일단 배포해서 확인해보겠습니다.)

feat: Add apiManager #58

---

src/api/apiManager.js

- axios header 에 authorization 키를 추가했습니다.

feat: Add authorization in headers #58

---

src/Pages/HomePage/index.jsx

- localStorage 함수에서 get 이 아닌 getItem 으로 수정했습니다.

fix: localStorage.getItem 으로 수정 #58

---

src/Pages/HomePage/index.jsx

fix: Add config in axios #58

---

src/Pages/HomePage/AttendanceButton.jsx
src/Pages/HomePage/AttendanceSummary.jsx
src/Pages/HomePage/TestButtons.jsx
src/Pages/HomePage/index.jsx

- axios 함수에 모두 config 옵션을 붙였습니다.

fix: Add jwt token config in axios function #58

---

src/Pages/HomePage/AttendanceTable.jsx

- 출석 기록 받아오는 axios 함수의 주석을 제거하고, 테스트용 더미 데이터를 지웠습니다.

fix: Delete dummy data #52

---

src/Pages/HomePage/AttendanceLog.jsx
src/Pages/HomePage/AttendanceSummary.jsx
src/Pages/HomePage/AttendanceTable.jsx
src/Pages/HomePage/index.jsx

fix: Add test console.log #52

---

src/Pages/Login.jsx

- 비밀번호 길이가 0 이면 "비밀번호를 입력해주세요." 메세지를 Alert 로 표시

fix: 비밀번호 길이가 0 이면 오류 메세지 띄워주기 #73

---

.github/workflows/develop-deploy.yml

- region 과 profile 을 명시해주었습니다. [참고자료](https://florian.ec/blog/github-actions-awscli-errors/)

docs: Add profile, region

---

src/pages/HomePage/AttendanceButton.jsx
src/pages/HomePage/AttendanceTable.css
src/pages/HomePage/AttendanceTable.jsx
src/pages/HomePage/index.jsx

- style: 출석체크 테이블 <th> 태그에 공통적으로 사용하는 CSS를 클래스로 지정하여 적용했습니다. (`.tableHeadText`)
- fix: 오늘의 단어를 틀리고 창을 닫았다가 다시 열었을 때 오류 메세지가 남아있는 현상을 수정했습니다.

Refactor/home page spliting#52

---

src/pages/HomePage/AttendanceButton.jsx
src/pages/HomePage/AttendanceSummary.jsx

- fix: 출석체크를 성공하면 개근 일수, 출석 기록을 새로고침 없이 업데이트 하도록 기능을 수정했습니다.
- fix: 출석체크를 성공하면 출석체크 버튼을 비활성화 시키고, 버튼 내부의 텍스트 메시지가 바뀌도록 수정했습니다.

Fix/update attendance data#86

---

src/pages/HomePage/AttendanceButton.jsx

- button width 를 50% 에서 auto로 수정했습니다.

style: 출석체크 버튼 텍스트에 따라 버튼 길이 늘어나도록 수정 #86

---

src/api/apiManager.js
src/pages/Auth.jsx
src/pages/HomePage/AttendanceButton.jsx
src/pages/HomePage/AttendanceLog.jsx
src/pages/HomePage/AttendanceSummary.jsx
src/pages/HomePage/SetTodayWordButton.jsx
src/pages/HomePage/TestButtons.jsx
src/pages/HomePage/index.jsx
src/pages/Login.jsx
src/pages/SignupPage/index.jsx

- refactor: axios 함수를 사용할 때 baseURL 과 jwt 토큰을 공통으로 설정하는 instance 를 생성했습니다.
- axios 대신`apiManager` 함수를 호출하면 axios 와 동일하게 작동합니다.
- 예시는 아래와 같습니다.
```JavaScript
const response = await apiManager.get(`/userAttendance`);
if (response.status === 200) {
...
}
```

Fix/create api manager#43

---

src/pages/Auth.jsx
src/pages/HomePage/AttendanceButton.jsx
src/pages/HomePage/AttendanceLog.jsx
src/pages/HomePage/AttendanceSummary.jsx
src/pages/HomePage/SetTodayWordButton.jsx
src/pages/HomePage/index.jsx

fix: apiManager API URL 마지막에 슬래시 추가 #95

---

src/pages/HomePage/AttendanceLog.jsx
src/pages/HomePage/AttendanceSummary.jsx

- 출석체크 페이지에서 개근 일수가 정상적으로 표시되지 않는 문제 해결

fix: Remove trailing slash #95

---

src/pages/HomePage/AttendanceButton.jsx
src/pages/SignupPage/index.jsx

- fix: 출석체크 -> 오늘의 단어 제출 시 request body 에 intraId 제거
- fix: 회원가입 시 request body 에 isOperator 변수 제거

Fix/remove intra id api#102

---

src/api/apiManager.js

- accessToken 이 존재하지 않으면 "" 값으로 설정합니다.

fix: jwt 토큰이 없으면 "" 값으로 설정 #43

---

src/pages/Login.jsx

- 회원가입 후 자동으로 아이디 채워지는 기능 및 비밀번호 자동 포커스 기능 제거

fix: Intra ID가 입력 폼에 자동으로 채워지지 않도록 수정 #98

---

src/pages/Auth.jsx
src/pages/Login.jsx
src/pages/SignupPage/index.jsx

- 회원가입이 성공하면 로그인 페이지 하단에 팝업창을 띄워주는 기능을 추가했습니다.

Feat/add signup complete message#107

---

src/pages/HomePage/AttendanceLog.jsx
src/pages/HomePage/AttendanceSummary.jsx
src/pages/HomePage/SetTodayWordButton.jsx
src/pages/HomePage/index.jsx

- 백엔드 요청 시 URL 에 포함했던 `_intraId` 를 삭제했습니다.
- `attendance/buttonStatus`
- `operator/setTodayWord`
- `statistic/userAttendanceList`
- `statistic/userAttendanceState`
- `user/getUserInfo`
- 오늘의 단어 설정 시 request body 에 포함했던 `intraId` 를 제거했습니다.

Fix/modify api url and request body#109

---

src/pages/SignupPage/index.jsx

fix: Remove photoUrl in signup #109

---

src/App.js
src/components/DesktopLayout.jsx
src/components/MobileLayout.jsx
src/pages/DashboardPage/index.jsx

- 이번 달 개근 여부 수정을 위한 merge
- 아직 레이아웃 작업은 끝나지 않음

Feat/admin page layout#118

---

src/pages/HomePage/AttendanceSummary.jsx

- isPerfect 가 아닌 isPerfectAttendance 로 수정

fix: 이번 달 개근 여부 변수명 수정 #119

---

src/pages/DashboardPage/DateSelector.jsx
src/pages/DashboardPage/index.jsx

- 연도, 월 선택하는 폼을 별도의 컴포넌트로 분리
- 조회 버튼 높이를 100% 로 설정

style: Add DateSelector.jsx #119

---

src/pages/HomePage/index.jsx

fix: LoginChecker 컴포넌트가 전체를 감싸지 않도록 수정#126

---

src/App.js
src/pages/Auth.jsx
src/pages/Login.jsx
src/pages/SignupPage/index.jsx
src/store.js

- _isClickedPasswordReset 상태 추가

feat: 비밀번호 초기화 버튼 여부 확인#133

---

src/App.js
src/components/DesktopLayout.jsx
src/pages/SettingPage/OperatorTable.jsx
src/pages/SettingPage/index.jsx

- feat: 오퍼레이터 권한 추가 테이블 생성
- 오퍼레이터 권한이 있는 유저가 맨 위로 오도록 정렬
- TODO: 버튼 클릭 시 오퍼레이터 권한 추가/제거 기능 추가 예정(백엔드 API 개발 필요)

Feat/grant operator#135

---

src/pages/SettingPage/OperatorTable.jsx

- 오퍼레이터 추가/제거 권한 API 주소 추가
- 권한 수정 시 주의사항 추가

feat: Add operator add/delete api #135

---

src/pages/DashboardPage/UserAttedanceDataTable.jsx

- DB 수정 테이블에서 유저가 존재하지 않으면 테이블이 표시되지 않도록 수정

fix: 존재하지 않는 유저 검색 시 테이블 표시하지 않도록 수정 #141

---

src/pages/Login.jsx
src/pages/SignupPage/index.jsx

- 로그인 페이지 및 회원가입 페이지 접근 시, 이미 로그인 된 상태라면 이전 페이지로 돌아가도록 설정

Fix/restrict login page#97

---

src/pages/HomePage/SetTodayWordButton.jsx
src/pages/HomePage/TodayWord.jsx
src/pages/HomePage/UserProfile.jsx
src/pages/HomePage/index.jsx

- feat: 오퍼레이터만 오늘의 단어를 볼 수 있도록 기능 추가
- feat: 오퍼레이터인 경우 인트라 아이디 하단에 파란색 글씨로 `Operator` 표시

Feat/display today word#148

---

package-lock.json
src/App.js
src/components/PublicRoute.jsx
src/components/ServerStatusCheck.jsx
src/pages/ClosedPage/ClosedPageLayout.jsx
src/pages/ClosedPage/index.jsx
src/pages/NotFoundPage/index.jsx
src/utils/getServerStatus.jsx
src/utils/isLogin.js

- feat: 서버가 꺼져있을 때 서버 운영 시간 안내 페이지 표시
- feat: 유효한 경로가 아닌 주소로 접속할 경우 Not found 페이지 표시

Feat/display closed page#150

---

src/pages/HomePage/AttendanceLog.jsx

- fix: 출석 날짜가 제대로 출력되지 않는 문제 해결

Fix/display attendance log in ascending order#152

---

src/pages/DashboardPage/MonthlyHalfPerfectUserTable.jsx
src/pages/DashboardPage/MonthlyUserTable.jsx
src/pages/DashboardPage/index.jsx

- 기능 추가
- 선택한 달의 1/2 개근 인원 수 표시
- 선택한 달의 1/2 개근 인원 테이블 추가 (csv export 가능)
- #158

Feat/monthly half perfect user list#158
